---

- name: Start EC2 instances
  ec2:
    aws_access_key: '{{ec2_access_key}}'
    aws_secret_key: '{{ec2_secret_key}}'

    region: '{{instance_region}}'
    group: '{{instance_group}}'
    image: ami-0c115dbd34c69a004
    instance_profile_name: '{{instance_iam_role}}'
    instance_type: '{{instance_type}}'
    key_name: '{{instance_key}}'
    wait: true
    instance_tags:
      Name: '{{instance_tag}}'
    count_tag:
      Name: '{{instance_tag}}'
    exact_count: 1
  register: ec2

- name: Print instance info
  debug:
    var: ec2
    verbosity: 1
