---

- name: 'Start {{ container_name }} container'
  docker_container:
    name: '{{ container_name }}'
    image: '{{ container_image }}'
    published_ports: '{{ container_ports }}'
    restart_policy: unless-stopped
