#!/bin/bash

if [[ ! "$OSTYPE" == "linux-gnu"* ]]; then
    echo "This script is only supported on Linux" >&2
    exit 1
fi

# for coverage analysis
rustup install nightly-gnu
cargo +nightly-gnu install grcov

# for release packaging
rustup target add x86_64-unknown-linux-gnu --toolchain stable
rustup target add x86_64-unknown-linux-musl --toolchain stable
