#!/bin/bash

if [[ ! "$OSTYPE" == "linux-gnu"* ]]; then
    echo "This script is only supported on Linux" >&2
    exit 1
fi

export CARGO_INCREMENTAL=0
export RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort"
export RUSTDOCFLAGS="-Cpanic=abort"

# cargo +nightly-gnu clean --target-dir target-nightly
cargo +nightly-gnu build --target-dir target-nightly
cargo +nightly-gnu test --target-dir target-nightly
cargo +nightly-gnu test --target-dir target-nightly -- --ignored

mkdir -p ./generated
rm -rf ./generated/coverage
grcov ./target-nightly/debug/ --source-dir . --output-type html --llvm --branch --ignore-not-existing -o ./generated/coverage/
