#!/bin/bash

if [[ ! "$OSTYPE" == "linux-gnu"* ]]; then
    echo "This script is only supported on Linux" >&2
    exit 1
fi

TARGET=x86_64-unknown-linux-gnu

cargo +stable build --bin server --release --target $TARGET
mkdir -p ./dist/

cp ./target/$TARGET/release/server ./dist/