#!/bin/bash

# pushd frontend > /dev/null
# bash ./script/bootstrap
# popd > /dev/null

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    pushd backend > /dev/null
    bash ./script/bootstrap_linux
    popd > /dev/null
fi
