#!/bin/bash

# pushd frontend > /dev/null
# bash ./script/coverage
# popd > /dev/null

if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    pushd backend > /dev/null
    bash ./script/coverage_linux
    popd > /dev/null
else
    echo "Backend coverage is only supported on Linux" >&2
fi

