#!/bin/bash

if [[ ! "$OSTYPE" == "linux-gnu"* ]]; then
    echo "This script is only supported on Linux" >&2
    exit 1
fi

if [[ -z "$AWS_ACCESS_KEY_ID" ]]; then
    echo "AWS_ACCESS_KEY_ID must be set" >&2
fi

if [[ -z "$AWS_SECRET_ACCESS_KEY" ]]; then
    echo "AWS_SECRET_ACCESS_KEY must be set" >&2
fi

if [[ -z "$AWS_ACCOUNT_ID" ]]; then
    echo "AWS_ACCOUNT_ID must be set" >&2
fi

REGION=eu-central-1
REGISTRY=$AWS_ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com
aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $REGISTRY

BRANCH=$(git rev-parse --abbrev-ref HEAD | sed "s/[\/-]/_/g")
COMMIT=$(git rev-parse --short HEAD)
IMAGE=nextreq
TAG=${BRANCH}-${COMMIT}

TARGET=${REGISTRY}/${IMAGE}:${BRANCH}-latest
docker tag ${IMAGE}:${TAG} $TARGET
docker push $TARGET

if [[ "$BRANCH" == "master" ]]; then
    TARGET=${REGISTRY}/${IMAGE}:latest
    docker tag ${IMAGE}:${TAG} $TARGET
    docker push $TARGET
fi
