#!/bin/bash

if [[ ! "$OSTYPE" == "linux-gnu"* ]]; then
    echo "This script is only supported on Linux" >&2
    exit 1
fi

pushd frontend > /dev/null
bash ./script/package
popd > /dev/null

pushd backend > /dev/null
bash ./script/package_linux
popd > /dev/null