#!/bin/bash

if [[ ! "$OSTYPE" == "linux-gnu"* ]]; then
    echo "This script is only supported on Linux" >&2
    exit 1
fi

pushd frontend > /dev/null
bash ./script/package
popd > /dev/null

pushd backend > /dev/null
bash ./script/package_linux
popd > /dev/null

BRANCH=$(git rev-parse --abbrev-ref HEAD | sed "s/[\/-]/_/g")
COMMIT=$(git rev-parse --short HEAD)
TAG="${BRANCH}-${COMMIT}"
IMAGE=nextreq

echo "Creating image ${IMAGE}:${TAG}"

docker build -t ${IMAGE}:${TAG} -f distribution/single_image/Dockerfile .
docker tag ${IMAGE}:${TAG} ${IMAGE}:${BRANCH}-latest

if [[ ! "$BRANCH" == "master" ]]; then
    docker tag ${IMAGE}:${TAG} ${IMAGE}:latest
fi
