name: Build and deploy docker image

on:
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Bootstrap
        run: bash ./script/bootstrap
      - name: Package
        run: bash ./script/package
      - name: List
        run: docker image ls
