name: Rust build and test

on:
  push:
    branches: "**"
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v3
        id: backend_diff
        with:
          PREFIX_FILTER: backend/

      - name: Build
        run: cargo build
        if: steps.backend_diff.outputs.diff

      - name: Run tests
        run: cargo test
        if: steps.backend_diff.outputs.diff

      - name: Check format
        run: cargo fmt --all -- --check
        if: steps.backend_diff.outputs.diff
